language: objective-c
before_install:
  - brew update
install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/homebrew-testtap
  - brew tap --repair
  - gem install rubocop
env:
  - PACKAGE=latexrun OPTIONS="--HEAD"
script:
  - rubocop --config=$(brew --repo)/Library/.rubocop.yml ${PACKAGE}.rb
  - if [ "$OPTIONS" != "--HEAD" ]; then brew audit $PACKAGE; fi
  - brew install -v $OPTIONS $PACKAGE
