language: objective-c
before_install:
  - brew update
install:
  - mkdir -p $(brew --repo)/Library/Taps/srstevenson
  - ln -s $PWD $(brew --repo)/Library/Taps/srstevenson/homebrew-formulae
  - brew tap --repair
  - gem install --no-document rubocop
env:
  - PACKAGE=latexrun OPTIONS="--HEAD"
  - PACKAGE=peat
  - PACKAGE=peat OPTIONS="--HEAD"
script:
  - rubocop --config=$(brew --repo)/Library/.rubocop.yml ${PACKAGE}.rb
  - if [ "$OPTIONS" != "--HEAD" ]; then brew audit $PACKAGE; fi
  - brew install -v $OPTIONS $PACKAGE
